### ISSUE TITLE
Using Exoplayer Amazon port? What is AMZNMediaPlayer?

### ISSUE THREAD

**Issue by brianchu** [amzn/fire-app-builder#11]
Is this project use code from https://github.com/amzn/exoplayer-amazon-port ?

I saw it include two jar in libs 
AMZNMediaPlayer.jar exoplayer.jar

What version is exoplayer.jar (1.?)
What is AMZNMediaPlayer?

**Comment by brian-ross** [comment]
This project is using version 1 of ExoPlayer. The update to version 2 is in progress. AMZNMediaPlayer is a media player that incorporates ExoPlayer and provides more functionality.
