### ISSUE TITLE
Project fails to build

### ISSUE THREAD

**Issue by EugeneSmoliy** [amzn/fire-app-builder#2]
There are multiple localization files (e. g. PassThroughAdsComponent/src/main/res/values-en-rUS/strings.xml) with following text "../values/strings.xml".
Due to this Gradle crashes with “Content is not allowed in prolog” error.
Removing these files solves the problem.

**Comment by sree466** [comment]
try cloning with the core.symlinks set to true.

git clone -c core.symlinks=true <URL>

**Comment by EugeneSmoliy** [comment]
It is mentioned in docs. Thanks!

**Comment by WeVolutionNet** [comment]
For GIT for Windows >= 2.5.0 the symlinks are configured in 2 locations.
Please check this post.
http://stackoverflow.com/questions/38326519/is-there-any-other-place-for-a-git-config-setting-other-than-global-system-and

**Comment by iLoveSarabear** [comment]
This... isn't working none of it is.

- I'm an Administrator
- symlinks are set to true
- %PROGRAMDATA%\Git\config symlinks=true

> fire-app-builder1\AdsInterface\src\main\res\values-en-rUS\strings.xml:1:1: Error: Content is not allowed in prolog.

What am I missing?
