### ISSUE TITLE
Subtitle to video

### ISSUE THREAD

**Issue by supriyatambe131995** [amzn/fire-app-builder#27]
How i can add subtitle to video

**Comment by supriyatambe131995** [comment]
Yes  i done this things but still not showing subtitle

**Comment by traviskroberts** [comment]
My app uses HLS video feeds that don't have inband closed captions (either CEA-608 or VTT). Reading through the source code, it appears to support mapping an array of URLs to `mCloseCaptionUrls` in my content feed. I've done that and I can even see in the logs where it says VTT captions are present and loaded, but they're still not displaying in the video player. Is there any documentation about how to use that `mCloseCaptionUrls` with VTT files?

**Comment by traviskroberts** [comment]
Actually, my solution works as long as I have `enableCEA608` set to "false" in `Navigator.json`!

**Comment by TheFloridaChannel** [comment]
But what if you have live 608 videos for live, but sidecar VTT for VOD? This "solution" seems to fix one issue by nerfing another ability. Currently I cannot get the app to play any captions from side car VTTs, ONLY embedded in the M3u8. Is that known by the team?
