### ISSUE TITLE
Design issue 

### ISSUE THREAD

**Issue by supriyatambe131995** [amzn/fire-app-builder#33]
hi 
how to find index of navigation activity i.e category(list bellow the search option) of video in FullContentBrowseActivity activity 

https://m.media-amazon.com/images/G/01/mobile-apps/dex/fireappbuilder/fireappbuilder_fullbrowse._TTH_.png

**Comment by levonlevonian** [comment]
Can you please describe your specific use case in more detail? What do you mean by "index of navigation activity" and how / where / for what would you like to use it? Thanks!
