### ISSUE TITLE
run simple android tv app on firestick os

### ISSUE THREAD

**Issue by supriyatambe131995** [amzn/fire-app-builder#34]
Hi,

Can we run android studio default tv app on firestick os if we used leanback libarary and exoplayer for video .

**Comment by levonlevonian** [comment]
Hi, yes, I believe so, it should be supported. Why do you ask -- are you getting any errors when trying to build or run the app on Fire TV Stick? If so, what specific errors are you seeing?

**Comment by supriyatambe131995** [comment]
I have issue while customise user interface and feed configuration that why I am planning to create new android TV app project.

**Comment by levonlevonian** [comment]
Sure, you can either go the Android Java app route, or try to modify / customize the Fire App Builder templates yourself. Thanks!

**Comment by supriyatambe131995** [comment]
Thank you
