### ISSUE TITLE
fire app builder UI customization

### ISSUE THREAD

**Issue by jay3395** [amzn/fire-app-builder#41]
can any one tell how to customize fire app builder UI ? for fire stick

**Comment by levonlevonian** [comment]
Hi Jay,

Could you please provide more details about what kind of customization are you looking for? Thanks!

**Comment by jay3395** [comment]
Hi, 
Fire app builder uses older version of leanback library "com.android.support:leanback-v17:23.1.1"  for making custom design i need to update leanback library.
So how do i update leanback library in fire app builder ?
here is clip:
(https://user-images.githubusercontent.com/26214193/53089228-f31dd900-3531-11e9-8af8-812904363040.png)

**Comment by jay3395** [comment]
> Hi Jay,
> 
> Could you please provide more details about what kind of customization you are looking for? Thanks!
