### ISSUE TITLE
MediaSession integration for "Alexa, pause" not working?

### ISSUE THREAD

**Issue by tmm1** [amzn/fire-app-builder#61]
I installed the sample Application in this repository to my FireTV Cube (AFTR). In the video player, if I say "Alexa, pause" it responds with "I don't know that".

The same thing happens with this sample amazon app too: https://www.amazon.com/gp/product/B07CMDMMP9

I have looked at `adb shell dumpsys media_session` and `adb shell dumpsys audio` to confirm audio focus and the MediaSession are setup correctly.

The documented requirements for voice control from https://developer.amazon.com/docs/fire-tv/mediasession-api-integration.html#integrating-with-media-session-for-voice-enabled-media-playback are already implemented in both these apps, yet the feature does not work. What's missing?

**Comment by levonlevonian** [comment]
Does that happen with other commands like "Alexa, play", or only with **Pause**? Do you see anything in the logs?

**Comment by tmm1** [comment]
None of the media session commands were working.

I had two echos paired to my FireTV acting as a home theater setup (https://www.androidcentral.com/how-pair-echo-speaker-fire-tv). Once I disconnected those it started working more reliably.
