### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by mrcool17** [amzn/fire-app-builder#65]
Incremental java compilation is an incubating feature.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.

please help me for solved this error

**Comment by Mariuxtheone** [comment]
Suggestion is to compile using the latest version of FAB. Closing this due to age and non specific feedback. Please reopen if you are still encountering the issue, providing Logcat feedback. Thanks.
