### ISSUE TITLE
Incoporate touch interaction with Fire APP Builder?

### ISSUE THREAD

**Issue by DerekWongMI** [amzn/fire-app-builder#71]
Anyone can give me pointers on how to incorporate touch interaction 
- as seen here https://developer.amazon.com/blogs/appstore/post/63ff3988-9d3d-44d5-bbec-111f46895669/how-to-add-touch-interactions-to-android-based-fire-tv-applications

Into the fire app builder?

**Comment by Mariuxtheone** [comment]
FAB is designed for remote, but by having an optimized layout based on Android development guidelines, the main UI works with touch enabled devices as well.
