### ISSUE TITLE
Live Stream Buffering 

### ISSUE THREAD

**Issue by damianemile** [amzn/fire-app-builder#81]
Hello, I finally got my fire app builder up and working, but for some reason my live stream on the fire app builder buffers, than starts than buffer again and after a while it’s just keep spinning.. 

I have this stream playing flawlessly in VLC, on my website as well as on Roku… I’m not sure what is causing this to buffer like this in this app.. 

I’m wondering if I can integrate exoplayer into this app if possible to see if it would make a difference?  Please help kindly to stop this buffering..

**Comment by damianemile** [comment]
Found an alternative way around :)

**Comment by brixxnatt** [comment]
how ??
