### ISSUE TITLE
Tons of errors

### ISSUE THREAD

**Issue by BlackAlbatros** [amzn/fire-app-builder#89]
How come hasn't this been updated since 2018? 
The current version here returns tons of errors and it's a nightmare to go thru this as a beginner.

**Comment by space-mudd** [comment]
Yes, I agree. No updates and no info how to  update the library to support the latest devices for the FireTV app builder.

**Comment by BlackAlbatros** [comment]
Closed?

**Comment by giolaq** [comment]
Hi @BlackAlbatros. I'm closing this as there is no specific request. Happy to consider issues with more details. Thank you

**Comment by BlackAlbatros** [comment]
Hi there.
Well... The thing is that the current version here is outdated. When i run this thru Android Studio i'm getting multiple issues. Should i place them here?

**Comment by giolaq** [comment]
Yes thank you!

**Comment by space-mudd** [comment]
> Closed?

No, we're still looking to update the libraries so the FireTV App Builder is compatible with the latest devices. How is this done?

**Comment by giolaq** [comment]
Hi @space-mudd can you reply on your issue with the specific problem or request you have? Can you also attach screenshots? Thank you

**Comment by space-mudd** [comment]
> Hi @space-mudd can you reply on your issue with the specific problem or request you have? Can you also attach screenshots? Thank you

Here is the error message... how can we update the app so it is compatible with the latest devices. 
[
![Reduced Device Support](https://github.com/amzn/fire-app-builder/assets/67874260/1e8a51fa-e66e-4af7-b809-b36cd8ad28fc)
](url)

**Comment by giolaq** [comment]
Try to follow the update procedure here https://developer.amazon.com/docs/fire-tv/fire-os-8.html#version_elements
